In [10]:
from sklearn.datasets import load_iris
iris = load_iris()
print("Feature names:", iris.feature_names)
print("Target names:", iris.target_names)
print("First 5 rows of data:\n", iris.data[:5])
print("First 5 labels:", iris.target[:5])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']
First 5 rows of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
First 5 labels: [0 0 0 0 0]


In [14]:
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
import numpy as np

# Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target
target_names = iris.target_names

# Pick one sample (e.g., index 0)
sample_idx = 0
sample = X[sample_idx].reshape(2, 2)  # reshape 4 features into 2x2 image

plt.figure(figsize=(4, 4))
plt.imshow(sample, cmap="viridis", interpolation="nearest")
plt.colorbar(label="Feature value")
plt.title(f"Iris sample {sample_idx} - {target_names[y[sample_idx]]}", fontsize=12)

# Add text annotations for feature values
for i in range(2):
    for j in range(2):
        plt.text(j, i, f"{sample[i, j]:.2f}",
                 ha="center", va="center", color="white", fontsize=10)

plt.axis("off")
plt.show()


FileNotFoundError: [Errno 2] No such file or directory: 'iris_flower.jpg'

In [7]:
from sklearn.datasets import load_digits
digits = load_digits()
print("Image data shape:", digits.data.shape)
print("Target labels:", digits.target[:25])


Image data shape: (1797, 64)
Target labels: [0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4]


In [4]:
import sklearn.datasets
print(dir(sklearn.datasets))

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_arff_parser', '_base', '_california_housing', '_covtype', '_kddcup99', '_lfw', '_olivetti_faces', '_openml', '_rcv1', '_samples_generator', '_species_distributions', '_svmlight_format_fast', '_svmlight_format_io', '_twenty_newsgroups', 'clear_data_home', 'data', 'descr', 'dump_svmlight_file', 'fetch_20newsgroups', 'fetch_20newsgroups_vectorized', 'fetch_california_housing', 'fetch_covtype', 'fetch_file', 'fetch_kddcup99', 'fetch_lfw_pairs', 'fetch_lfw_people', 'fetch_olivetti_faces', 'fetch_openml', 'fetch_rcv1', 'fetch_species_distributions', 'get_data_home', 'load_breast_cancer', 'load_diabetes', 'load_digits', 'load_files', 'load_iris', 'load_linnerud', 'load_sample_image', 'load_sample_images', 'load_svmlight_file', 'load_svmlight_files', 'load_wine', 'make_biclusters', 'make_blobs', 'make_checkerboard', 'make_circles', 'make_classificat

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 1. Static dataset (numbers 1 to 100)
X = [[i] for i in range(1, 101)]
y = [1 if i > 50 else 0 for i in range(1, 101)]  # label = 1 if > 50 else 0

# 2. Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=20, stratify=y
)

# 3. Train Logistic Regression
model = LogisticRegression()
model.fit(X_train, y_train)

# 4. Predict
y_pred = model.predict(X_test)
a = model.predict([[30], [60], [90]])

print("Test Predictions:", y_pred[:10])
print("True labels:", y_test[:10])
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Custom Predictions:", a)

print("data", y_test)

Test Predictions: [0 0 0 0 1 1 0 0 0 0]
True labels: [0, 0, 0, 0, 1, 1, 0, 0, 0, 0]
Accuracy: 1.0
Custom Predictions: [0 1 1]
data [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1]


In [17]:
'''std scaler'''
from sklearn.preprocessing import StandardScaler
import numpy as np

# Sample dataset: 3 features
data = np.array([
    [1.0, 200.0, 1000.0],
    [2.0, 300.0, 2000.0],
    [3.0, 400.0, 3000.0],
    [4.0, 500.0, 4000.0]
])

print("Original Data:\n", data)

# Initialize StandardScaler
scaler = StandardScaler()

# Fit and transform
scaled_data = scaler.fit_transform(data)

print("\nScaled Data:\n", scaled_data)

# Means and standard deviations used
print("\nMean:", scaler.mean_)
print("Scale (std dev):", scaler.scale_)


Original Data:
 [[1.e+00 2.e+02 1.e+03]
 [2.e+00 3.e+02 2.e+03]
 [3.e+00 4.e+02 3.e+03]
 [4.e+00 5.e+02 4.e+03]]

Scaled Data:
 [[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]

Mean: [   2.5  350.  2500. ]
Scale (std dev): [   1.11803399  111.80339887 1118.03398875]


In [21]:
from sklearn.preprocessing import LabelEncoder

colors = ["red", "green", "blue", "green", "red"]
le = LabelEncoder()
encoded = le.fit_transform(colors)
print(encoded)


[2 1 0 1 2]


In [20]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

data = np.array([["red"], ["green"], ["blue"], ["red"]])
encoder = OneHotEncoder()
encoded = encoder.fit_transform(data).toarray()
print(encoded)


[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
