In [10]:
import numpy as np
a= np.array([12, 24, 16, 21, 32, 29, 7, 15])
r1=a>20
print(r1)
r2=a[r1]
print(r2)

[False  True False  True  True  True False False]
[24 21 32 29]


In [8]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b1 = b% 2 != 0
result =b[b1]
print(result)

[1 3 5 7 9]


In [11]:
c = np.array([1, 2, 4, 9, 11, 16, 18, 22, 26, 31, 33, 47, 51, 52])
c1= (c < 10) | (c> 40)
result = c[c1]
print(result)

[ 1  2  4  9 47 51 52]


In [17]:
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
d1= d.copy()
d1[d % 2 == 0] = 0
print(d1)

[1 0 3 0 5 0 7 0 9 0]


In [20]:
x = np.array([[1, 7, 9],
                    [14, 19, 21],
                    [25, 29, 35]])

# create a boolean mask based on the condition
# that elements are greater than 9
x1 = x > 9
print(x1)
r1 = x[x1]
print(r1)

[[False False False]
 [ True  True  True]
 [ True  True  True]]
[14 19 21 25 29 35]
