In [4]:
import numpy as np
'''np broadcasting'''
a=np.array([1,2,3,])#1d
b=np.array([[4],[5],[6]])#2d
#adding array of different dimension
#size of a1 expands to match a2 matrix style addition
sum=a+b
print(sum)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [8]:
'''creating matrix'''
m1=np.array([[1,2],[3,4]])#2x2 matrix
m2=np.array([[[5,6,7],[7,8,9],[10,11,12]]])#3x3 matrix
print('2d',m1)
print('3d',m2)


2d [[1 2]
 [3 4]]
3d [[[ 5  6  7]
  [ 7  8  9]
  [10 11 12]]]


In [16]:
'''matrix multiplication'''
a1=np.array([[1,3],[5,7]])
b1=np.array([[2,6],[4,8]])
c1=a1*b1
c2=np.dot(a1,b1)
c3=np.multiply(a1,b1)
print('normal multiplication')
print(c3)
print(c1)
print('matrix multiplication')
print(c2)

normal multiplication
[[ 2 18]
 [20 56]]
[[ 2 18]
 [20 56]]
matrix multiplication
[[14 30]
 [38 86]]


In [18]:
'''transpose matrix'''
a=np.transpose([[1,2],[3,4]])
print(a)

[[1 3]
 [2 4]]


In [20]:
'''inverse matrix'''
a=np.linalg.inv([[1,2],[3,4]])
print(a)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [26]:
'''determinant matrix'''
a=np.linalg.det([[1,2],[3,4]])#ad-cb i.e 1*4-2*3
print(a)
#3d determinant
import numpy as np

matrix1 = np.array([[1, 2, 3],
             		[4, 5, 6],
                    [7, 8 , 11]])
#Step-by-step using cofactor expansion (along the first row):
#det(𝐴)=𝑎11(𝑀11)-𝑎12(𝑀12)+𝑎13(𝑀13)
# find determinant of matrix1
result = np.linalg.det(matrix1)


print(result)

-2.0000000000000004
-6.0


In [27]:
''''flatten matrix'''
a1=np.array([[1,3],[5,7]])
r1=a1.flatten()
print(r1)


[1 3 5 7]
