In [5]:
#creating 2d array
import numpy as np
array=np.array([[1,2,3,4,],
                [6,7,8,9,]])
array[1]


array([6, 7, 8, 9])

In [6]:
array

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [7]:
a=array[1][1]
print(a)
#acces certain value


7


In [8]:
td=np.array([[[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12]],

          [[13,14,15,16],
           [17,18,19,20],
           [21,22,23,24]]])
print(td)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [9]:
print(td[0][1][2])
#first will select slice 1 or 2 second will select row third column


7


In [10]:
#2d array with zero
c=np.zeros((3,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#3d array with zero
d=np.zeros((3,3,3))
print(d)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [12]:
#create full array with element
a=np.full((3,3,5),1)
print(a)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [13]:
#creating random  2d array and empty
a=np.random.random((3,3,3))
print(a)
print('empty')
b=np.empty((3,3,3))
print(b)

[[[0.88000595 0.80523204 0.43162464]
  [0.79021711 0.86341174 0.5458514 ]
  [0.57803904 0.27359337 0.35528659]]

 [[0.61492695 0.63960015 0.58208047]
  [0.62144295 0.77105247 0.90884287]
  [0.73707681 0.66822278 0.29836725]]

 [[0.63915621 0.33434214 0.58455264]
  [0.96333243 0.46864743 0.18239021]
  [0.06734147 0.19702575 0.10923393]]]
empty
[[[0.88000595 0.80523204 0.43162464]
  [0.79021711 0.86341174 0.5458514 ]
  [0.57803904 0.27359337 0.35528659]]

 [[0.61492695 0.63960015 0.58208047]
  [0.62144295 0.77105247 0.90884287]
  [0.73707681 0.66822278 0.29836725]]

 [[0.63915621 0.33434214 0.58455264]
  [0.96333243 0.46864743 0.18239021]
  [0.06734147 0.19702575 0.10923393]]]
