In [3]:
import numpy as np
'''gor 1d'''
a=np.array([1,2,3])
b=a+10
print(b)


[11 12 13]


In [5]:
'''for 2d'''
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[7,8,9],[10,11,12]])
r1=a1+a2
print(r1)

[[ 8 10 12]
 [14 16 18]]


In [13]:
'''numpy loop'''
'''using python list'''
import time
start = time.time()
print('start time', start)
a = [1, 2, 3, 4, 5]
for i in range(len(a)):
    a[i] += 10
    print(a)

print('outside loop')
print(a)

end = time.time()
print('end time',end)

print("For loop time:", end - start)

start time 1754301569.3777914
[11, 2, 3, 4, 5]
[11, 12, 3, 4, 5]
[11, 12, 13, 4, 5]
[11, 12, 13, 14, 5]
[11, 12, 13, 14, 15]
outside loop
[11, 12, 13, 14, 15]
end time 1754301569.3798208
For loop time: 0.0020294189453125


In [15]:
'''using numpy'''
start = time.time()
print('start time', start)
a1 = np.array([1, 2, 3, 4, 5 ])
result = a1 + 10
end = time.time()
print('end time',end)

print("Vectorization time:", end - start)

start time 1754301758.8260868
end time 1754301758.826586
Vectorization time: 0.0004992485046386719


In [28]:
print('numpy function ')
a = np.array([-1, 2, 0, 4, 5])
def square(x):
    if x < 0:
        return 0
    else:
         return x**2
r1=np.vectorize(square)
result=r1(a)
print(result)


numpy function 
[ 0  4  0 16 25]
