In [37]:
import numpy as np
#1d to 2d
a=np.array([1,2,3,4,5,6,7,8,])
b2=np.reshape(a,(2,4))
print(b2)

print('1d to 3d')
c3=np.reshape(a,(2,2,2))
print(c3)



[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
