In [1]:
import numpy as np
#for type
a=np.array([1,2,3])
b=np.array([[1,2,3,4,],
                [6,7,8,9,]])
c=np.array([[[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12]],

          [[13,14,15,16],
           [17,18,19,20],
           [21,22,23,24]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)


1
2
3


In [5]:
#for size
print(a.size)
print(b.size)
print(c.size)

3
8
24


In [7]:
#slice , row ,column by shape
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 4)
(2, 3, 4)


In [30]:
#size in bytes
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)
'''changing item size'''
td=a.astype(np.int32)
print(td.itemsize)

8
8
8
4


In [15]:
#memory address of data
print(a.data)
print(b.data)
print(c.data)

In [33]:
#saving file in np
np.save('numpy',a)#file creation in same dictionary might need refreshing in mu computer
np.save('demot',b)


In [37]:
#loading file created by save function
Aa=np.load('numpy.npy')
Bb=np.load('demot.npy')
print(Aa)
print(Bb)

[1 2 3]
[[1 2 3 4]
 [6 7 8 9]]


In [39]:
'''creating file in txt format'''
Aaa=np.savetxt('a.txt',a)
Bbb=np.savetxt('b.txt',b)


In [45]:
'''loading txt file'''
k=np.loadtxt('a.txt')
l=np.loadtxt('b.txt')
print(k)
print(l)

[1. 2. 3.]
[[1. 2. 3. 4.]
 [6. 7. 8. 9.]]
