In [3]:
print('hello world')
import numpy as np
my_array = np.array([1,2,3,4,5])
print(my_array)
# can acess arrray similar to list in python

print('creating new array using addition')
#if we try this operation in list it will simply include 5
new_array=my_array+5
print(new_array)
a=[1,2,3,4,5]+[10]
print(a)






hello world
[1 2 3 4 5]
creating new array using addition
[ 6  7  8  9 10]
[1, 2, 3, 4, 5, 10]


In [4]:
print(my_array)

[1 2 3 4 5]


In [5]:
#creating array multiple zeros
array=np.zeros(5)
array

array([0., 0., 0., 0., 0.])

In [6]:
array1=np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
#creating array with range with  increment
array2=np.arange(7,24,3)
print(array2)

[ 7 10 13 16 19 22]


In [8]:
#creating random array
array3=np.random.random(5)
print(array3)


[0.04620744 0.10394298 0.23301625 0.03974481 0.57743764]


In [9]:
array4=np.empty(5)
print(array4)
#numpy will add random value but it does not have significance

[0.04620744 0.10394298 0.23301625 0.03974481 0.57743764]


In [10]:
# accessing data type in np
n=np.array([1,2,3,4,5])
j=np.array({1,2,3,4,5})
k=np.array(['a','b','c','d','e'])
l=np.array([-1,-2,-3,-4,-5])
m=np.array([0.1,0.2,0.3,0.4,0.5])
print(n.dtype)
print(j.dtype)
print(k.dtype)
print(l.dtype)
print(m.dtype)

int64
object
<U1
int64
float64


In [15]:
'''converting numpy array to another tyoe'''
a_array=np.array([1,2,3,4,5])
print(a_array)
print(a_array.dtype)
b=a_array.astype(np.float64)
print(b.dtype)
print(b)

[1 2 3 4 5]
int64
float64
[1. 2. 3. 4. 5.]
