In [2]:
import numpy as np
"trignometry"
angles =np.array([30,60,90])
print(angles)
sin = np.sin(angles)
cos = np.cos(angles)
tan = np.tan(angles)
print(sin)
print(cos)
print(tan)
# we need to convert into radian to get std value

[30 60 90]
[-0.98803162 -0.30481062  0.89399666]
[ 0.15425145 -0.95241298 -0.44807362]
[-6.4053312   0.32004039 -1.99520041]


In [3]:
ag=1.570796
a1=np.degrees(ag)
print(a1)

89.99998127603166


In [4]:
'''round function'''
numbers = np.array([1.23456, 2.34567, 3.45678, 4.56789])

# round the array to two decimal places
rounded_array = np.round(numbers, 2)

print(rounded_array)

# Output: [1.23 2.35 3.46 4.57]


[1.23 2.35 3.46 4.57]


In [5]:
'''floor function'''

array1 = np.array([1.23456, 2.34567, 3.45678, 4.56789])

print("Array after floor():", np.floor(array1))

#convert to nearest integer


print("Array after ceil():", np.ceil(array1))

Array after floor(): [1. 2. 3. 4.]
Array after ceil(): [2. 3. 4. 5.]


In [9]:
print('numpy constant')
'''pi'''
y=np.pi
print(y)
radius=2
circumference=2*np.pi*radius
print(circumference)



numpy constant
3.141592653589793
12.566370614359172


In [12]:
x=np.e
print(x)
'expansion bu e '
z=2
l=np.exp(z)
print(l)
# z can be any number


2.718281828459045
7.38905609893065


In [22]:
print('numpy stat')
'''2d median'''
b=np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print(np.median(b))# overall median
r1=np.median(b,axis=0)
print(r1)#verticle axis median
r2=np.median(b,axis=1)
print(r2)# horizontal axis median


numpy stat
5.5
[3.5 4.5 5.5 6.5 7.5]
[3. 8.]


In [23]:
'''Mean'''
a=np.array([1,2,3,4,5])
a1=np.mean(a)
print(a1)

'''2d mean'''
b=np.array([[1,2,3,4,],
                [6,7,8,9,]])
b1=np.mean(b,axis=0)
print(b1)
b2=np.mean(b,axis=1)
print(b2)
b3=np.mean(b)
print(b3)

3.0
[3.5 4.5 5.5 6.5]
[2.5 7.5]
5.0


In [30]:
'''np percentile'''
az=np.array([0,1,19,26,39,41,55,78])
az1=np.percentile(az,100)
print(az1)
az2=np.percentile(az,90)
print(az2)
az3=np.percentile(az,50)
print(az3)


78.0
61.9
32.5


In [31]:
'''np min and max'''
az=np.array([0,1,19,26,39,41,55,78])
az1=np.min(az)
print(az1)
az2=np.max(az)
print(az2)

0
78
