In [5]:
import numpy as np
from sympy.codegen.cxxnodes import using

'''addition'''
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
ab=np.add(a,b)
print(ab)

[5 7 9]
[5 7 9]


In [8]:
'''subtraction '''
print(a-b)
a_b=np.subtract(b,a)
print(a_b)

[-3 -3 -3]
[3 3 3]


In [10]:
'''multiplication'''
print(a*b)
axb=np.multiply(a,b)
print(axb)

[ 4 10 18]
[ 4 10 18]


In [12]:
'''division'''
print(a/b)
adb=np.divide(b,a)
print(adb)

[0.25 0.4  0.5 ]
[4.  2.5 2. ]


In [17]:
'''exponentiation'''
print(a**b)
aabb=np.power(a,b)
print(aabb)

[  1  32 729]
[  1  32 729]


In [19]:
'''modulus'''
print(a%b)
amb =np.mod(a,b)
print(amb)

[1 2 3]
[1 2 3]


In [22]:
'''mean'''
x=np.array([19,27,38,44,56,78])
mean=np.mean(x)
print(mean)


43.666666666666664


In [24]:
'''median'''
median=np.median(x)
print(median)


41.0


In [25]:
'''transpose'''
originalArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# if axes argument is skipped, the shape of array is reversed
transposedArray = np.transpose(originalArray)

print(transposedArray)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
