In [2]:
import numpy as np
A = np.array([1, 3, 5])
B = np.array([0, 2, 3])

# union of two arrays
result = np.union1d(A, B)

print(result)

# Output: [0 1 2 3 5]

[0 1 2 3 5]


In [4]:
'''intersection'''
r1 = np.intersect1d(A, B)#giving only common value
print(r1)

[3]


In [8]:
'''difference'''
r2 = np.setdiff1d(A, B)
#A-B gives value of A excludes common values
print(r2)
print('b-a')
r3 = np.setdiff1d(B, A)
#B-A gives value of B excludes common values
print(r3)

[1 5]
b-a
[0 2]


In [10]:
'''symmetry difference'''
r4 = np.setxor1d(A,B)
#gives matrix with uncommon value
print(r4)

[0 1 2 5]


In [11]:
'''uniq'''
array1 = np.array([1,1, 2, 2, 4, 7, 7, 3, 5, 2, 5])
# unique values from array1
result = np.unique(array1)

print(result)

# Output: [1 2 3 4 5 7]

[1 2 3 4 5 7]
