In [3]:
'''For a graph like this, with elements A, B and C, the connections are:

A & B are connected with weight 1.

A & C are connected with weight 2.

C & B is not connected.

The Adjency Matrix would look like a:'''
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix
'''connected components'''
a = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

a1 = csr_matrix(a)

print(connected_components(a1))

(1, array([0, 0, 0], dtype=int32))


In [5]:
b = np.array([
  [0, 1, 0,0],
  [1, 0, 0,0],
  [0, 0, 0,1],
  [0, 0, 1,0]
])

b1 = csr_matrix(b)

print(connected_components(b1))

(2, array([0, 0, 1, 1], dtype=int32))


In [ ]:
'''Dijkstra
 dijkstra method used to find the shortest path in a graph from one element to another.'''
 ''' graph would look like
    (0)
   /   \
  10    3
 /       \
(1)---1--(2)
  \       |
   2      8
    \     |
     (3)--(4)
        7
Path1= 0 → 1 → 3 → 4

Path2= 0 → 2 → 4

Path3= 0 → 1 → 2 → 4

We want to compute shortest paths from node 0.
will try example
'''

In [11]:
import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix
c = [
    [0, 10, 3, 0, 0],  # edges from node 0
    [10, 0, 1, 2, 0],  # edges from node 1
    [3, 1, 0, 0, 8],   # edges from node 2
    [0, 2, 0, 0, 7],   # edges from node 3
    [0, 0, 8, 7, 0]    # edges from node 4
]
c1=csr_matrix(c)
print(dijkstra(c1, return_predecessors=True, indices=0))


(array([ 0.,  4.,  3.,  6., 11.]), array([-9999,     2,     0,     1,     2], dtype=int32))


In [12]:
'''This gives the minimum distance from source node (0) to each node:

0. → Distance from 0 to 0 = 0

4. → Distance from 0 to 1 = 4

3. → Distance from 0 to 2 = 3

6. → Distance from 0 to 3 = 6

11. → Distance from 0 to 4 = 11

So, for example, the shortest path from node 0 to node 3 is length 6.
array([-9999,     2,     0,     1,     2], dtype=int32)
This tells you which node was the previous step on the shortest path.

-9999 → means no predecessor (that’s for the source itself, node 0).

2 → To reach node 1 optimally, you come from node 2.

0 → To reach node 2 optimally, you come from node 0.

1 → To reach node 3 optimally, you come from node 1.

2 → To reach node 4 optimally, you come from node 2.'''


'This gives the minimum distance from source node (0) to each node:\n\n0. → Distance from 0 to 0 = 0\n\n4. → Distance from 0 to 1 = 4\n\n3. → Distance from 0 to 2 = 3\n\n6. → Distance from 0 to 3 = 6\n\n11. → Distance from 0 to 4 = 11\n\nSo, for example, the shortest path from node 0 to node 3 is length 6.\narray([-9999,     2,     0,     1,     2], dtype=int32)\nThis tells you which node was the previous step on the shortest path.\n\n-9999 → means no predecessor (that’s for the source itself, node 0).\n\n2 → To reach node 1 optimally, you come from node 2.\n\n0 → To reach node 2 optimally, you come from node 0.\n\n1 → To reach node 3 optimally, you come from node 1.\n\n2 → To reach node 4 optimally, you come from node 2.'

In [14]:
'''Floyd Warshall'''
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix
print(floyd_warshall(c1, return_predecessors=True))


(array([[ 0.,  4.,  3.,  6., 11.],
       [ 4.,  0.,  1.,  2.,  9.],
       [ 3.,  1.,  0.,  3.,  8.],
       [ 6.,  2.,  3.,  0.,  7.],
       [11.,  9.,  8.,  7.,  0.]]), array([[-9999,     2,     0,     1,     2],
       [    2, -9999,     1,     1,     2],
       [    2,     2, -9999,     1,     2],
       [    2,     3,     1, -9999,     3],
       [    2,     2,     4,     4, -9999]], dtype=int32))


In [17]:
'''depth first order and breadth first order'''
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import depth_first_order
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import depth_first_order, breadth_first_order

graph = [
    [0, 1, 1, 0, 0, 0],  # 0 connected to 1 and 2
    [1, 0, 0, 1, 1, 0],  # 1 connected to 0,3,4
    [1, 0, 0, 0, 0, 1],  # 2 connected to 0,5
    [0, 1, 0, 0, 0, 0],  # 3 connected to 1
    [0, 1, 0, 0, 0, 0],  # 4 connected to 1
    [0, 0, 1, 0, 0, 0]   # 5 connected to 2
]

newarr = csr_matrix(graph)

# Depth First Search
dfs_order, dfs_predecessors = depth_first_order(newarr, 0)

# Breadth First Search
bfs_order, bfs_predecessors = breadth_first_order(newarr, 0)

print("DFS order:", dfs_order)
print("DFS predecessors:", dfs_predecessors)

print("\nBFS order:", bfs_order)
print("BFS predecessors:", bfs_predecessors)



DFS order: [0 1 3 4 2 5]
DFS predecessors: [-9999     0     0     1     1     2]

BFS order: [0 1 2 3 4 5]
BFS predecessors: [-9999     0     0     1     1     2]


In [ ]:
'''Interpretation
DFS (Depth First Search)

Goes as deep as possible before backtracking.

Order: [0 → 1 → 3 → 4 → 2 → 5]

Explores down one branch (0 → 1 → 3), then backtracks to visit 4, then jumps to 2 → 5.

BFS (Breadth First Search)

Explores level by level.

Order: [0 → 1 → 2 → 3 → 4 → 5]

Visits all neighbors of 0 first (1 and 2), then their children (3,4,5).'''