In [ ]:
from binascii import b2a_qp

'''Sparse data is data that has mostly unused elements (elements that don't carry any information ).
It can be an array like this one:
[1, 0, 2, 0, 0, 3, 0, 0, 0, 0, 0, 0]
Sparse Data: is a data set where most of the item values are zero.'''

In [3]:
'''CSR - Compressed Sparse Row. For fast row slicing, faster matrix vector products'''
import numpy as np
from scipy.sparse import csr_matrix
a=np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])
print(a)
print(csr_matrix(a))


[0 0 0 0 0 1 1 0 2]
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (1, 9)>
  Coords	Values
  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


In [7]:
'''with 2d'''
b= np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])
print(b)
print(csr_matrix(b))
print('counting non zero')
print(csr_matrix(b).count_nonzero())


[[0 0 0]
 [0 0 1]
 [1 0 2]]
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (1, 2)	1
  (2, 0)	1
  (2, 2)	2
counting non zero
3


In [9]:
'''eliminating non zero'''
b1=(csr_matrix(b))
b1.eliminate_zeros()
print(b1)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [12]:
'''CSC - Compressed Sparse Column. For efficient arithmetic, fast column slicing.
Converting from csr to csc with the tocsc() method:'''
print(b)
print(csr_matrix(b))

b2=csr_matrix(b).tocsc()
print(b2)


[[0 0 0]
 [0 0 1]
 [1 0 2]]
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (1, 2)	1
  (2, 0)	1
  (2, 2)	2
<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (2, 0)	1
  (1, 2)	1
  (2, 2)	2
